name: "linear_regression"
backend: "python"
max_batch_size: 8

input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 2 ]  # [x1, x2]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]  # [y]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

dynamic_batching {
  preferred_batch_size: [ 4 ]
  max_queue_delay_microseconds: 100
} 